application: fccextract
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /admin/.*
  script: admin.py
  login: admin

- url: /jquery.js
  static_files: jquery.js
  upload: jquery.js

- url: /(.*).png
  static_files: \1.png
  upload: .*.png

- url: /visual_test/.*
  script: visual_test.py

- url: /.*
  script: main.py

